# tasks file for app

---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!"

- include: puma.yml
- include: ruby.yml
- include: deploy.yml
