---
- name: Install MongoDB 4.2
  hosts: all
  become: true
  tasks:
  - name: Add key
    apt_key:
       url: https://www.mongodb.org/static/pgp/server-4.2.asc
       state: present

  # Подключаем репозиторий с пакетами mongodb
  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
      state: present

  # Выполним установку пакетов
  - name: Install packages
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - mongodb-org

  # Включаем сервис
  - name: Configure mongod service
    systemd:
      name: mongod
      enabled: yes
