---
- name: Install Ruby && Bundler
  hosts: all
  become: true
  tasks:
    - name: Install git, ruby and required packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - git
          - ruby-full
          - ruby-bundler
          - build-essential
